name: unloved
favicon: null
layout_spectrum: 0
typography_spectrum: 0.93306
title: the unloved
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#bf6917'
    - '#0f0801'
    - '#271504'
    - '#301a05'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
